### ISSUE TITLE
Can we add lumia930? It is also msm8974

### ISSUE THREAD

**Issue by qaz6750** [msm8974-mainline/linux#3]

**Comment by z3ntu** [comment]
If you have a dts for it, feel free to open a PR.

**Comment by qaz6750** [comment]
But he can't start pm8941 correctly at present

**Comment by z3ntu** [comment]
Sorry, I don't understand your comment.

**Comment by qaz6750** [comment]
Pm8941 regulators cannot have

regulator-always-on;

regulator-boot-on

Otherwise he will not be able to start Linux

**Comment by qaz6750** [comment]
for example
![屏幕截图 2022-06-04 170950](https://user-images.githubusercontent.com/66907230/171992700-b9b210fa-4a9e-47c2-af53-24187a71fb7c.jpg)
However, if it is used in the node, for example, it cannot be started, and it is stuck in the logs of pm8941 regulators

![屏幕截图 2022-06-04 171016](https://user-images.githubusercontent.com/66907230/171992768-0b7c1111-2b2f-4055-aa7a-67efd0045869.jpg)

**Comment by qaz6750** [comment]
ok ,My maybe can add dts
