### ISSUE TITLE
Upstream OnePlus One dts

### ISSUE THREAD

**Issue by z3ntu** [msm8974-mainline/linux#4]
Please someone with the device test the branch https://github.com/msm8974-mainline/linux/commits/qcom-msm8974-5.19.y-bacon (not sure if the defconfig there is complete, could also use the one from pmaports) and confirm every single supported feature.

- [ ] ADSP
- [ ] Charger - FIXME: Is smbb or bq24196 used as charger? Both?
- [ ] Coincell charger
- [ ] Fuel gauge
- [ ] Internal storage
- [ ] Modem
- [ ] Touchscreen
- [ ] UART - FIXME: Both blsp1_uart1 and blsp1_uart2 are referenced. Which one is actually used?
- [ ] USB
- [ ] Wifi/Bluetooth

@Kaned1as @julian-goldsmith @valentino-sm

If you need any help, please let me know!

**Comment by Kaned1as** [comment]
I can't test it since I left the device in Russia when I skedaddled 🥲

**Comment by rhjdvsgsgks** [comment]
hi, im trying to port nixos mobile to bacon with this kernel. and i found someone can help me to test. currently, seems like Internal storage and Touchscreen works fine. USB peripheral mode works. but otg not (missing 5v output). Wifi still testing, but at least able to see the wlan0 interface

**Comment by z3ntu** [comment]
@rhjdvsgsgks What branch have you used there?

**Comment by rhjdvsgsgks** [comment]
> What branch have you used there?

v5.19.17-msm8974 tag with kernel config from pmaports

**Comment by z3ntu** [comment]
Okay good. I'd also like to ask you to test some other things out, so we can push some things upstream and don't have to maintain them directly in this repo anymore. Could you join our Matrix channel by any chance? https://matrix.to/#/#mainline:postmarketos.org Otherwise also Telegram or IRC would work for me. It's a bit easier to communicate there compared to GitHub.

**Comment by rhjdvsgsgks** [comment]
seems like there is some issue about mac address. it default to 00:00:00:00:00, which will cause iwd not working. even set mac addr maunally. 5g and ieee80211w are also not working, both of them will try to use "Hardware Address". so i have to disable them to connect network. maybe we need some patch like this? https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1776491
btw, wpa3 works fine with wpa_supplicant. but need to disable ieee80211w
ps, i joined irc channel. maybe i should send a message to you on it?

**Comment by z3ntu** [comment]
Devicetree patch is sent upstream, tested on v6.0.9

https://lore.kernel.org/linux-arm-msm/20221127181835.806410-1-luca@z3ntu.xyz/

Removed modem for now because I couldn't get it working, it was continuously crashing with stock firmware, although I did actually boot and appear in modemmanager with FP2 modem firmware.

**Comment by z3ntu** [comment]
This is merged upstream, closing.

**Comment by rhjdvsgsgks** [comment]
i found that wifi issue solved by using lk2nd. it will set `local-mac-address` on the fly ([maybe here](https://github.com/msm8916-mainline/lk2nd/blob/6e1debaf0e41684ee0bd2b99967c175b069e5e7c/platform/msm_shared/dev_tree.c#L1461)). thanks for you mainline it.

ps, i just send you a query on irc

**Comment by z3ntu** [comment]
I don't see any message from you
