### ISSUE TITLE
ARM: dts: qcom: msm8974-lge-hammerhead: remoteproc is disabled

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8974-mainline/linux#9]
Ref:
https://github.com/msm8974-mainline/linux/blob/v6.4.0-msm8974-wip/arch/arm/boot/dts/qcom-msm8974.dtsi#L1511
https://github.com/msm8974-mainline/linux/blob/v6.4.0-msm8974-wip/arch/arm/boot/dts/qcom-msm8974-lge-nexus5-hammerhead.dts#L345-L354
https://lore.kernel.org/linux-arm-msm/20221121212226.321514-2-luca@z3ntu.xyz/
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/4200

**Comment by z3ntu** [comment]
Can you please test with commit https://github.com/msm8974-mainline/linux/commit/3ce71e1c8c57a39b40e523aa3a7f3c72ed24e244 ?

Also the pinctrl conflict of gpio54 should be resolved now with https://github.com/msm8974-mainline/linux/commit/3e0b90891ab953cab1fa5dcc32ca2a3c0c3cf39c

**Comment by wonderfulShrineMaidenOfParadise** [comment]
> Can you please test with commit [3ce71e1](https://github.com/msm8974-mainline/linux/commit/3ce71e1c8c57a39b40e523aa3a7f3c72ed24e244) ?

I tried it on 6.3 and the modem is enabled again. No idea if cellular actually works, though.
I can also try it on 6.4 if it's preferred.

> 
> Also the pinctrl conflict of gpio54 should be resolved now with [3e0b908](https://github.com/msm8974-mainline/linux/commit/3e0b90891ab953cab1fa5dcc32ca2a3c0c3cf39c)

~~Perhaps we can try to move cd pinctrl to boards. https://github.com/torvalds/linux/commit/dfbda20dabaa1f284abd550035db5887384c8e4c~~
Done in https://github.com/torvalds/linux/commit/1dfe967ec7cfb03b468d096a69d945070f1cd2a0

**Comment by z3ntu** [comment]
I also booted up my hammerhead and seems fine on mine as well. Thanks for reporting, I'm considering this fixed. Will send upstream soonish I hope.
